"FROM php:8.2-fpm-alpine" 
"RUN apk add --no-cache nginx curl mysql-client git supervisor && docker-php-ext-install pdo_mysql opcache" 
"COPY --from=composer:latest /usr/bin/composer /usr/bin/composer" 
"WORKDIR /var/www/html" 
"COPY . ." 
"RUN composer install --no-dev --optimize-autoloader" 
"RUN chown -R www-data:www-data /var/www/html/storage && chmod -R 775 /var/www/html/storage" 
